### ISSUE TITLE
Do not include toplevel printer installation in the base library

### ISSUE THREAD

**Issue by dbuenzli** [ryanrhymes/owl#99] opened 2017-09-06 07:01 UTC
It is customary to have a dedicated library for this (if `ocaml` and `ocamlfind` had better conventions no library should be needed but that's another problem). 

The fact that you use the toplevel API in the library, means that it's not possible to load `owl` in the native toplevel `ocamlnat` (the native toplevel API unfortunately has a separate API, see [MPR 7589](https://caml.inria.fr/mantis/view.php?id=7589)).

I'd advise to follow the toplevel scheme of `gg`, see the files `gg_top*` [here](https://github.com/dbuenzli/gg/tree/master/src) and the `META` [here](https://github.com/dbuenzli/gg/blob/a1cd31593c744c6a2473e81a4fbc2b4b1956273f/pkg/META#L9-L18).

After this you have two ocamlfind packages, `owl` and `owl.top` which users can `require` either for having the bare library or to have owl plus its toplevel support. Bonus point, you'll get rid of [these offensive](https://github.com/ryanrhymes/owl/blob/f51a5ce805e6987be7e1df60fc3b4ed6d2e4b124/lib/owl_toplevel.ml#L13-L18) `Obj.magic`s.

/cc @mars0i
More context https://discuss.ocaml.org/t/dynamically-link-native-code-into-utop/793

**Comment by ryanrhymes** [comment] 2017-09-06 13:30
Cool, Daniel, thank you very much for pointing it out, and really appreciate the detailed information you linked. I have gone through the pages, and yes I will separate the `toplevel` functions from the base library as you suggested.

For the discussion about the customised `utop`, it might make sense to make a customised one for the zoo system, since it might solve the issue of nested `#zoo` directives.

**Comment by mars0i** [comment] 2017-09-06 14:10
Thanks Liang.  (It was my attempt to use Owl in ocamlnat that led to this issue.)

**Comment by ryanrhymes** [comment] 2017-09-06 15:01
OK, I see. I will split toplevel function out of the base library as Daniel suggested. Then it should work.

**Comment by ryanrhymes** [comment] 2017-09-12 19:55
This has been solved. Now Zoo system will serve as Owl's customised toplevel and scripting environment. To install all the pretty printers and import Owl, you only need to

```ocaml
#require "owl_zoo";;
```

**Comment by ryanrhymes** [comment] 2017-09-25 17:17
@mars0i in the end, the toplevel part is in `owl_top`, `owl_zoo` will be another component soly focussing on composing high-level services, sharing and deploying services (in future). This decision also solved a couple of issues in the example scripts.

So in case you need Owl's pretty printing in toplevel, use the following code.

```ocaml
#require "owl_top";;
```

My apologies for the inconvenience caused by the many significant changes recently, but the purpose is getting this library better and better.

**Comment by ryanrhymes** [comment] 2017-09-25 17:19
I think this issue has been addressed so I am closing it. In case you spot any related issues, please reopen this one or open a new issue. Thanks for all the feedback and helps again.

**Closed by ryanrhymes** 2017-09-25 17:19 UTC
Labels: enhancement
